// Copyright © 2018, Meta Company.  All rights reserved.
// 
// Redistribution and use of this software (the "Software") in binary form, without modification, is 
// permitted provided that the following conditions are met:
// 
// 1.      Redistributions of the unmodified Software in binary form must reproduce the above 
//         copyright notice, this list of conditions and the following disclaimer in the 
//         documentation and/or other materials provided with the distribution.
// 2.      The name of Meta Company (“Meta”) may not be used to endorse or promote products derived 
//         from this Software without specific prior written permission from Meta.
// 3.      LIMITATION TO META PLATFORM: Use of the Software is limited to use on or in connection 
//         with Meta-branded devices or Meta-branded software development kits.  For example, a bona 
//         fide recipient of the Software may incorporate an unmodified binary version of the 
//         Software into an application limited to use on or in connection with a Meta-branded 
//         device, while he or she may not incorporate an unmodified binary version of the Software 
//         into an application designed or offered for use on a non-Meta-branded device.
// 
// For the sake of clarity, the Software may not be redistributed under any circumstances in source 
// code form, or in the form of modified binary code – and nothing in this License shall be construed 
// to permit such redistribution.
// 
// THIS SOFTWARE IS PROVIDED BY THE COPYRIGHT HOLDER "AS IS" AND ANY EXPRESS OR IMPLIED WARRANTIES, 
// INCLUDING, BUT NOT LIMITED TO, THE IMPLIED WARRANTIES OF MERCHANTABILITY AND FITNESS FOR A 
// PARTICULAR PURPOSE ARE DISCLAIMED.  IN NO EVENT SHALL META COMPANY BE LIABLE FOR ANY DIRECT, 
// INDIRECT, INCIDENTAL, SPECIAL, EXEMPLARY, OR CONSEQUENTIAL DAMAGES (INCLUDING, BUT NOT LIMITED TO, 
// PROCUREMENT OF SUBSTITUTE GOODS OR SERVICES; LOSS OF USE, DATA OR PROFITS; OR BUSINESS 
// INTERRUPTION) HOWEVER CAUSED AND ON ANY THEORY OF LIABILITY, WHETHER IN CONTRACT, STRICT 
// LIABILITY, OR TORT (INCLUDING NEGLIGENCE OR OTHERWISE) ARISING IN ANY WAY OUT OF THE USE OF THIS 
// SOFTWARE, EVEN IF ADVISED OF THE POSSIBILITY OF SUCH DAMAGE.
// automatically generated by the FlatBuffers compiler, do not modify

namespace types.fbs
{

using System;
using FlatBuffers;

public struct FrameHands : IFlatbufferObject
{
  private Table __p;
  public ByteBuffer ByteBuffer { get { return __p.bb; } }
  public static FrameHands GetRootAsFrameHands(ByteBuffer _bb) { return GetRootAsFrameHands(_bb, new FrameHands()); }
  public static FrameHands GetRootAsFrameHands(ByteBuffer _bb, FrameHands obj) { return (obj.__assign(_bb.GetInt(_bb.Position) + _bb.Position, _bb)); }
  public void __init(int _i, ByteBuffer _bb) { __p.bb_pos = _i; __p.bb = _bb; }
  public FrameHands __assign(int _i, ByteBuffer _bb) { __init(_i, _bb); return this; }

  public types.fbs.BufferHeader? Header { get { int o = __p.__offset(4); return o != 0 ? (types.fbs.BufferHeader?)(new types.fbs.BufferHeader()).__assign(__p.__indirect(o + __p.bb_pos), __p.bb) : null; } }
  public types.fbs.HandData? RightHand { get { int o = __p.__offset(6); return o != 0 ? (types.fbs.HandData?)(new types.fbs.HandData()).__assign(__p.__indirect(o + __p.bb_pos), __p.bb) : null; } }
  public types.fbs.HandData? LeftHand { get { int o = __p.__offset(8); return o != 0 ? (types.fbs.HandData?)(new types.fbs.HandData()).__assign(__p.__indirect(o + __p.bb_pos), __p.bb) : null; } }

  public static Offset<FrameHands> CreateFrameHands(FlatBufferBuilder builder,
      Offset<types.fbs.BufferHeader> headerOffset = default(Offset<types.fbs.BufferHeader>),
      Offset<types.fbs.HandData> right_handOffset = default(Offset<types.fbs.HandData>),
      Offset<types.fbs.HandData> left_handOffset = default(Offset<types.fbs.HandData>)) {
    builder.StartObject(3);
    FrameHands.AddLeftHand(builder, left_handOffset);
    FrameHands.AddRightHand(builder, right_handOffset);
    FrameHands.AddHeader(builder, headerOffset);
    return FrameHands.EndFrameHands(builder);
  }

  public static void StartFrameHands(FlatBufferBuilder builder) { builder.StartObject(3); }
  public static void AddHeader(FlatBufferBuilder builder, Offset<types.fbs.BufferHeader> headerOffset) { builder.AddOffset(0, headerOffset.Value, 0); }
  public static void AddRightHand(FlatBufferBuilder builder, Offset<types.fbs.HandData> rightHandOffset) { builder.AddOffset(1, rightHandOffset.Value, 0); }
  public static void AddLeftHand(FlatBufferBuilder builder, Offset<types.fbs.HandData> leftHandOffset) { builder.AddOffset(2, leftHandOffset.Value, 0); }
  public static Offset<FrameHands> EndFrameHands(FlatBufferBuilder builder) {
    int o = builder.EndObject();
    return new Offset<FrameHands>(o);
  }
  public static void FinishFrameHandsBuffer(FlatBufferBuilder builder, Offset<FrameHands> offset) { builder.Finish(offset.Value); }
};


}
